from __future__ import annotations

UMDIO_BASE = "https://api.umd.io/v1"
PLANETTERP_BASE = "https://planetterp.com/api/v1"
JUPITERP_BASE = "https://api.jupiterp.com/v0"

DEFAULT_SEMESTER = "202508"

LAMBDA_ASSIGN = 100.0
LAMBDA_OVERLAP = 200.0

DEFAULT_PROFESSOR_RATING = 3.0
DEFAULT_GPA = 3.0

WALKING_SPEED_MPS = 1.33
PATH_MULTIPLIER = 1.3

CACHE_TTL_BUILDINGS = 86400
CACHE_TTL_COURSES = 3600
CACHE_TTL_PROFESSORS = 3600

QAOA_DEPTH = 1
QAOA_SHOTS = 1000
QAOA_MAX_ITER = 50
MAX_BRUTE_FORCE_VARS = 22
